let selectedStation=null,loadedTrains=[],mapReady=false,currentView=0;const gate=document.getElementById("stationGate"),views=[...document.querySelectorAll(".view")],navButtons=[...document.querySelectorAll(".nav-btn[data-target]")],bottomNav=document.getElementById("bottomNav"),sheet=document.getElementById("bottomSheet"),backdrop=document.getElementById("sheetBackdrop");
function setView(i){currentView=Math.max(0,Math.min(2,i));gate.hidden=true;views.forEach((v,n)=>v.classList.toggle("active",n===currentView));navButtons.forEach((b,n)=>b.classList.toggle("active",n===currentView));if(currentView===1)setTimeout(()=>{initMap();renderMap()},40)}
navButtons.forEach(b=>b.addEventListener("click",()=>setView(Number(b.dataset.target))));
function showGate(){views.forEach(v=>v.classList.remove("active"));gate.hidden=false;bottomNav.hidden=true}function renderStationGrid(){const e=document.getElementById("stationGrid");e.innerHTML=stations.map(s=>`<button class="station-pick-btn" data-station="${s.name}"><span class="station-mark"></span><strong>${s.name}</strong></button>`).join("");e.querySelectorAll("[data-station]").forEach(b=>b.addEventListener("click",()=>selectStation(b.dataset.station)))}
function selectStation(n){selectedStation=n;document.getElementById("selectedStationLabel").textContent=`${n}駅`;bottomNav.hidden=false;renderDualRoute();setView(0)}
function openSheet(t,b){document.getElementById("sheetTitle").textContent=t;document.getElementById("sheetBody").innerHTML=b;sheet.hidden=false;backdrop.hidden=false;requestAnimationFrame(()=>{sheet.classList.add("open");backdrop.classList.add("open")})}function closeSheet(){sheet.classList.remove("open");backdrop.classList.remove("open");setTimeout(()=>{sheet.hidden=true;backdrop.hidden=true},180)}document.getElementById("sheetClose").addEventListener("click",closeSheet);backdrop.addEventListener("click",closeSheet);
const routeSide=t=>t.rawDirection==="上り"?"up":"down";const trainChip=t=>`<button class="track-train ${routeSide(t)}" data-train="${t.id}"><span class="train-emoji">🚃</span><strong>${t.id}</strong><small>${t.nickname}</small></button>`;
function renderDualRoute(){const e=document.getElementById("dualRoute");let h=`<div class="route-columns-head"><span>上り<br><b>熊本方面</b></span><span>駅</span><span>下り<br><b>三角方面</b></span></div>`;stations.forEach((s,i)=>{const at=loadedTrains.filter(t=>t.currentStation===t.nextStation?t.currentStation===s.name:(t.positionIndex>=i&&t.positionIndex<i+1)),l=at.filter(t=>routeSide(t)==="up"),r=at.filter(t=>routeSide(t)==="down");h+=`<div class="route-node ${s.name===selectedStation?"selected":""}"><div class="side left">${l.map(trainChip).join("")}</div><button class="center-station" data-station="${s.name}"><i></i><strong>${s.name}</strong></button><div class="side right">${r.map(trainChip).join("")}</div></div>`});e.innerHTML=h;e.querySelectorAll("[data-train]").forEach(b=>b.addEventListener("click",()=>openTrainDetail(b.dataset.train)));e.querySelectorAll("[data-station]").forEach(b=>b.addEventListener("click",()=>selectStation(b.dataset.station)))}
function openTrainDetail(id){const t=loadedTrains.find(x=>x.id===id);if(!t)return;const rows=t.timetable.map((r,i)=>{const f=i===t.timetable.length-1,time=f?r.arrival:(r.departure||r.arrival);return `<div class="schedule-row ${f?"final":""}"><span class="schedule-dot"></span><div><strong>${r.station}</strong><small>${f?"終着":"停車駅"}</small></div><b>${time}</b><em>${f?"着":"発"}</em></div>`}).join("");openSheet(`${t.id} ${t.nickname}`,`<div class="train-detail-summary"><div><span>現在位置</span><strong>${t.currentStation===t.nextStation?t.currentStation+"駅":t.currentStation+" → "+t.nextStation}</strong></div><div><span>方面</span><strong>${t.displayDirection}</strong></div><div><span>現在時刻</span><strong>10:30</strong></div></div><h3 class="sheet-subtitle">ここから終着駅までの予定</h3><div class="remaining-schedule">${rows}</div>${t.operationalState==="出発待ち" ? `<div class="inference-note"><strong>判定：</strong>ビーコン発信から5分以上経過し、三角駅に停車したままのため「上り・出発待ち」と判定しています。</div>` : ""}
    <p class="source-note">${t.timetableNote}</p>`)}
function renderTimeReference(){document.getElementById("timeReference").innerHTML=loadedTrains.map(t=>`<article class="time-ref-card"><div class="time-ref-head"><strong>${t.id}</strong><span>${t.nickname}</span></div>${t.timetable.map(r=>`<div class="time-ref-row"><b>${r.station}</b><span>${r.arrival?`着 ${r.arrival}`:""}</span><span>${r.departure?`発 ${r.departure}`:""}</span></div>`).join("")}<small>${t.timetableNote}</small></article>`).join("")}
function getRoutePoints(){if(Array.isArray(lightweightRouteSegments)&&lightweightRouteSegments.length){const p=[];lightweightRouteSegments.forEach((s,si)=>{if(!s||!Array.isArray(s.points))return;s.points.forEach((x,i)=>{if(si>0&&i===0)return;if(Array.isArray(x)&&Number.isFinite(x[0])&&Number.isFinite(x[1]))p.push(x)})});if(p.length>1)return p}return stations.map(s=>[s.lat,s.lng])}
function mapProjection(){const r=getRoutePoints(),a=r.concat(stations.map(s=>[s.lat,s.lng])),la=a.map(p=>p[0]),lo=a.map(p=>p[1]),minLa=Math.min(...la),maxLa=Math.max(...la),minLo=Math.min(...lo),maxLo=Math.max(...lo),pad=34,width=720,height=500,project=(lat,lng)=>[pad+((lng-minLo)/Math.max(.000001,maxLo-minLo))*(width-pad*2),pad+((maxLa-lat)/Math.max(.000001,maxLa-minLa))*(height-pad*2)];return{width,height,project}}
function initMap(){const e=document.getElementById("map");if(!e)return;const{width,height,project}=mapProjection(),pts=getRoutePoints().map(p=>project(p[0],p[1]).join(",")).join(" "),ss=stations.map(s=>{const[x,y]=project(s.lat,s.lng);return `<g class="svg-station ${s.name===selectedStation?"selected":""}"><circle cx="${x}" cy="${y}" r="${s.name===selectedStation?8:5.5}"></circle><text x="${x+9}" y="${y+14}">${s.name}</text></g>`}).join("");e.innerHTML=`<svg id="routeSvgMap" class="svg-route-map" viewBox="0 0 ${width} ${height}"><polyline class="svg-route-halo" points="${pts}"></polyline><polyline class="svg-route-line" points="${pts}"></polyline>${ss}<g id="svgTrainLayer"></g></svg>`;mapReady=true}
function renderMap(){if(!mapReady)initMap();const l=document.getElementById("svgTrainLayer");if(!l)return;const{project}=mapProjection();l.innerHTML=loadedTrains.map(t=>{const[x,y]=project(t.latitude,t.longitude);return `<g class="svg-train" transform="translate(${x} ${y})"><circle r="16" class="svg-train-circle"></circle><text x="0" y="6" text-anchor="middle">🚃</text><rect class="svg-train-label-bg" x="-46" y="-44" width="92" height="23" rx="11"></rect><text class="svg-train-label" x="0" y="-29" text-anchor="middle">${t.id}</text></g>`}).join("")}
const scales=[{s:1,l:"文字：標準"},{s:1.18,l:"文字：大"},{s:.9,l:"文字：小"}];let scaleIndex=0;document.getElementById("fontBtn").addEventListener("click",()=>{scaleIndex=(scaleIndex+1)%scales.length;document.documentElement.style.setProperty("--font-scale",scales[scaleIndex].s);document.getElementById("fontBtn").textContent=scales[scaleIndex].l});
async function init(){loadedTrains=await loadTrainData();renderStationGrid();renderTimeReference();renderDualRoute();initMap();renderMap();setTimeout(()=>{const s=document.getElementById("splashScreen");s.classList.add("hide");document.body.classList.remove("splash-active");setTimeout(()=>s.remove(),350)},1200)}init().catch(console.error);